const DealListingTypeEnum = {
  ITEM_FOR_SALE: 'DEAL01',
  VEHICLE_FOR_SALE: 'DEAL02',
  PROPERTY_FOR_SALE: 'DEAL03',
  JOB_OPENING: 'DEAL04',
  SERVICE_FOR_SALE: 'DEAL05',
  PACKAGE_FOR_SALE: 'DEAL06',
  HOME_SERVICE: 'DEAL07',
  GALLERY: 'DEAL08',
  GROCERY: 'DEAL09',
  RETAIL: 'DEAL10',
  CONVENIENCE: 'DEAL11',
  GIFTS: 'DEAL12',
  FLOWERS: 'DEAL13',
  STORES: 'DEAL14',
  FOOD: 'DEAL15',
  DOWNLOADS: 'DEAL16'
};

export default DealListingTypeEnum;
